### ISSUE TITLE
Módulo de boletos sem gerar boleto

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#31]
Ontem e hoje tentei gerar um boleto. Ontem simplesmente aparecia uma página de erro do Chrome, sem informação.

Hoje surgiu essa msg:

TypeError: Cannot call method 'substring' of undefined
    at Object.Billet.barCode (/home/ubuntu/eekit/billets/model/Itau.js:241:19)
    at /home/ubuntu/eekit/billets/model/Itau.js:117:34
    at Object.Billet.validate (/home/ubuntu/eekit/billets/model/Itau.js:73:5)
    at Object.Billet.print (/home/ubuntu/eekit/billets/model/Itau.js:91:10)
    at Billet.print (/home/ubuntu/eekit/billets/model/Billet.js:54:18)
    at module.exports (/home/ubuntu/eekit/billets/controller/Billet.js:43:16)
    at callbacks (/home/ubuntu/eekit/billets/node_modules/express/lib/router/index.js:165:11)
    at param (/home/ubuntu/eekit/billets/node_modules/express/lib/router/index.js:139:11)
    at pass (/home/ubuntu/eekit/billets/node_modules/express/lib/router/index.js:146:5)
    at Router._dispatch (/home/ubuntu/eekit/billets/node_modules/express/lib/router/index.js:173:5)

**Comment by luizpiovesana** [comment]
http://empreendekit.com.br:8009/billet?receiver=Empreendemia&cpfCnpj=10679087000129&bankId=341&agency=1619&account=33538&accountVD=1&wallet=175&agreement=&value=293.36.00&creationDate=Thu%20Mar%2007%202013%2000:00:00%20GMT-0300%20(Hora%20oficial%20do%20Brasil)&dueDate=Fri%20Mar%2008%202013%2000:00:00%20GMT-0300%20(Hora%20oficial%20do%20Brasil)&clientName=Zocprint&demonstrative=Leads&instructions=N%C3%A3o%20aceitar%20ap%C3%B3s%20o%20vencimento.

**Comment by mauro0x52** [comment]
Considerei como Hotfix
